### ISSUE TITLE
Datatype of `.snakemake-workflow-catalog.yml` > `mandatory-flags` > `flags`

### ISSUE THREAD

**Issue by charmoniumQ** [snakemake/snakemake-workflow-catalog#19]
The [documentation](https://github.com/snakemake/snakemake-workflow-catalog/blob/main/index.html#L326) says to put your flags in this variable. Should they be stored as a list of flags or a string?

```yaml
usage:
  mandatory-flags:
    flags: "--profile test"
---

usage:
  mandatory-flags:
    flags: ["--profile", "test"]
```
