### ISSUE TITLE
catalog builds, but `Deploy` action is not triggered automatically by the `Generate catalog` push action

### ISSUE THREAD

**Issue by m-jahn** [snakemake/snakemake-workflow-catalog#38]
- apparently a push from one github workflow does not trigger `on: push: [main]` from another workflow
- need to use a dedicated trigger instead [as described here](https://stackoverflow.com/questions/62750603/github-actions-trigger-another-action-after-one-action-is-completed):

```
on:
  workflow_run:
    workflows: ["workflow name"]
    types:
      - completed
```
